### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by huiyang0613** [hsp-iit/sim2real-surface-classification#1]
Thanks for this very nice work!
I am wondering if there is a code release planned?

**Comment by gabrielecaddeo** [comment]
Hi @huihui0613 ,
Thanks for your interest! The paper is currently under review, that's why the code is not released. We will update the repository once we have news from the conference.

**Comment by huiyang0613** [comment]
ok~ I'm going to look forward to it.

**Comment by gabrielecaddeo** [comment]
Hi @huiyang0613 , code will be released within 10 days!

**Comment by huiyang0613** [comment]
:) thanks

**Comment by gabrielecaddeo** [comment]
@huiyang0613  Code release started! Me and my colleagues will proceed with pull requests and merge from other branches, but you can start looking at the code. First demo available next week
